#!/usr/bin/env bash
# Lean LazyVim installer for Debian/Ubuntu and Fedora.
# Neovim itself must already be installed (./install.sh --neovim or ./install-fedora.sh --neovim).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"
# shellcheck source=lib/nvim-profile.sh
source "$SCRIPT_DIR/lib/nvim-profile.sh"

LAZYVIM_MIN_NEOVIM="0.11.2"
EXTRAS_FILE="$NVIM_CONFIG_DIR/lua/plugins/dotfiles-extras.lua"

usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

Lean LazyVim setup (web, config, shell, Python, Markdown).
Does NOT install Neovim, Rust, LLVM, or C++ toolchains.

Options:
  --dry-run       Print actions without changing the system
  --skip-sync     Skip headless LazyVim plugin sync
  -h, --help      Show this help

Configuration: lazyvim/install.conf
EOF
}

parse_args() {
  SKIP_SYNC=0

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --dry-run) DRY_RUN=1 ;;
      --skip-sync) SKIP_SYNC=1 ;;
      -h | --help)
        usage
        exit 0
        ;;
      *)
        die "unknown option: $1"
        ;;
    esac
    shift
  done
}

version_ge() {
  printf '%s\n%s\n' "$2" "$1" | sort -C -V
}

check_neovim() {
  local version luajit_ok=0

  command -v nvim >/dev/null 2>&1 || die "nvim not found. Run: ./install.sh --neovim  or  ./install-fedora.sh --neovim"

  version="$(nvim --version | head -n 1 | sed -n 's/.*NVIM v\([0-9.]*\).*/\1/p')"
  [[ -n "$version" ]] || die "could not parse nvim version"

  if ! version_ge "$version" "$LAZYVIM_MIN_NEOVIM"; then
    die "nvim $version is too old (LazyVim requires >= $LAZYVIM_MIN_NEOVIM)"
  fi

  if nvim --version | grep -qi luajit; then
    luajit_ok=1
  fi

  if [[ "$luajit_ok" -ne 1 ]]; then
    die "nvim must be built with LuaJIT (LazyVim requirement)"
  fi

  log "neovim OK: $(nvim --version | head -n 1)"
}

check_node_environment() {
  if ! truthy "$REQUIRE_NODE"; then
    log "skipping Node.js requirement (REQUIRE_NODE=false)"
    return 0
  fi

  load_nvm_into_shell || true

  if command -v node >/dev/null 2>&1 && command -v npm >/dev/null 2>&1; then
    log "node OK: $(node --version), npm $(npm --version)"
    return 0
  fi

  if ! truthy "${INSTALL_NVM_IF_MISSING:-true}"; then
    die "node/npm missing and INSTALL_NVM_IF_MISSING=false"
  fi

  if truthy "${PROMPT_NVM_INSTALL:-true}"; then
    if [[ "$DRY_RUN" -eq 1 ]]; then
      log "would prompt to install Node.js via nvm"
    elif [[ -t 0 ]]; then
      echo
      echo "Node.js is required for the LazyVim web development profile."
      echo "The nvm installer will ask which Node major version to use (latest x.y.z in that line)."
      if ! prompt_yes "Install Node.js via nvm now?"; then
        die "install Node with ./scripts/nvm-install-update.sh or set REQUIRE_NODE=false"
      fi
    fi
  fi

  log "starting nvm installer (interactive version selection)"
  run bash "$SCRIPT_DIR/install-nvm-node.sh"
  load_nvm_into_shell || true

  if command -v node >/dev/null 2>&1 && command -v npm >/dev/null 2>&1; then
    log "node OK: $(node --version), npm $(npm --version)"
    return 0
  fi

  die "node/npm are required but not available after nvm install attempt"
}

write_dotfiles_extras() {
  local tmp content

  mkdir -p "$(dirname "$EXTRAS_FILE")"
  tmp="$(mktemp)"

  {
    cat <<'EOF'
-- Generated by lazyvim/install-lazyvim.sh
-- Edit lazyvim/install.conf and re-run the installer to change extras.
-- LazyVim-lite ignores this file (profile-aware guard).

local profile = require("config.nvim-profile")
if not profile.is("lazyvim") then
  return {}
end

return {
  { import = "lazyvim.plugins.extras.lang.typescript" },
  { import = "lazyvim.plugins.extras.lang.python" },
  { import = "lazyvim.plugins.extras.lang.json" },
  { import = "lazyvim.plugins.extras.lang.yaml" },
  { import = "lazyvim.plugins.extras.lang.toml" },
  { import = "lazyvim.plugins.extras.lang.tailwind" },
  { import = "lazyvim.plugins.extras.lang.git" },
EOF

    if truthy "$ENABLE_DOCKER"; then
      echo '  { import = "lazyvim.plugins.extras.lang.docker" },'
    fi
    if truthy "$ENABLE_MARKDOWN_TOOLS"; then
      echo '  { import = "lazyvim.plugins.extras.lang.markdown" },'
    fi
    if truthy "$ENABLE_VUE"; then
      echo '  { import = "lazyvim.plugins.extras.lang.vue" },'
    fi
    if truthy "$ENABLE_SVELTE"; then
      echo '  { import = "lazyvim.plugins.extras.lang.svelte" },'
    fi
    if truthy "$ENABLE_ASTRO"; then
      echo '  { import = "lazyvim.plugins.extras.lang.astro" },'
    fi
    if truthy "$ENABLE_ANGULAR"; then
      echo '  { import = "lazyvim.plugins.extras.lang.angular" },'
    fi

    echo "}"
  } >"$tmp"

  if [[ -f "$EXTRAS_FILE" ]] && cmp -s "$tmp" "$EXTRAS_FILE"; then
    rm -f "$tmp"
    log "LazyExtras config unchanged"
    return 0
  fi

  if [[ "$DRY_RUN" -eq 1 ]]; then
    log "would write $EXTRAS_FILE"
    cat "$tmp"
    rm -f "$tmp"
    return 0
  fi

  mv "$tmp" "$EXTRAS_FILE"
  log "wrote LazyExtras imports: $EXTRAS_FILE"
}

prepare_lazyvim_config() {
  log "linking LazyVim nvim config"
  link_nvim_lazyvim_config
  log "enabling LazyVim nvim profile"
  if [[ "$DRY_RUN" -eq 1 ]]; then
    run set_nvim_profile "lazyvim"
  else
    set_nvim_profile "lazyvim"
  fi

  write_dotfiles_extras
}

verify_installation() {
  local sync_ok=1 parser_ok=1 mason_ok=1
  local ts_bin="${HOME}/.local/bin/tree-sitter"

  load_nvm_into_shell || true
  ensure_local_bin_path

  log "verification"

  command -v nvim >/dev/null 2>&1 || record_fail "nvim missing"
  command -v git >/dev/null 2>&1 || record_fail "git missing"
  command -v curl >/dev/null 2>&1 || record_fail "curl missing"
  command -v rg >/dev/null 2>&1 || record_fail "rg missing"
  command -v cc >/dev/null 2>&1 || command -v gcc >/dev/null 2>&1 || record_fail "C compiler missing"

  # shellcheck source=../scripts/lib/platform.sh
  source "$DOTFILES_DIR/scripts/lib/platform.sh"
  # shellcheck source=lib/tree-sitter-verify.sh
  source "$SCRIPT_DIR/lib/tree-sitter-verify.sh"
  verify_tree_sitter_cli_for_install "$ts_bin" || true
  if [[ "${TS_CLI_VERIFY_STATUS:-fail}" == "fail" ]]; then
    parser_ok=0
  fi

  if [[ "$SKIP_SYNC" -eq 0 && "$DRY_RUN" -eq 0 ]]; then
    if ! nvim --headless "+checkhealth lazy" +qa >/tmp/lazyvim-health-lazy.log 2>&1; then
      sync_ok=0
      record_fail "checkhealth lazy failed (see /tmp/lazyvim-health-lazy.log)"
    fi

    if ! verify_nvim_tree_sitter_runtime /tmp/lazyvim-health-ts.log; then
      parser_ok=0
    fi

    if ! nvim --headless "+checkhealth mason" +qa >/tmp/lazyvim-health-mason.log 2>&1; then
      mason_ok=0
      record_fail "checkhealth mason failed (see /tmp/lazyvim-health-mason.log)"
    fi
  fi

  print_summary "$sync_ok" "$parser_ok" "$mason_ok"
  [[ "$FAILED" -eq 0 ]] || exit 1
}

print_summary() {
  local sync_ok="$1" parser_ok="$2" mason_ok="$3"
  local fd_path enabled_extras

  fd_path="$(command -v fd 2>/dev/null || command -v fdfind 2>/dev/null || echo missing)"
  enabled_extras="$(grep -o 'lazyvim.plugins.extras[^"]*' "$EXTRAS_FILE" 2>/dev/null | tr '\n' ' ' || echo unknown)"

  cat <<EOF

=== LazyVim setup summary ===
Neovim version:     $(command_version nvim --version)
Tree-sitter CLI:    $(command_version tree-sitter --version)
Tree-sitter path:   $(command -v tree-sitter 2>/dev/null || echo missing)
C compiler path:    $(command -v cc 2>/dev/null || command -v gcc 2>/dev/null || echo missing)
Git version:        $(command_version git --version)
ripgrep version:    $(command_version rg --version)
fd version:         $(command -v fd >/dev/null && fd --version | head -n1 || command -v fdfind >/dev/null && fdfind --version | head -n1 || echo missing)
Node version:       $(command -v node >/dev/null && node --version || echo not required/missing)
LazyVim config:     ${XDG_CONFIG_HOME:-$HOME/.config}/nvim
LazyVim data:       ${XDG_DATA_HOME:-$HOME/.local/share}/nvim
Enabled LazyExtras: ${enabled_extras}

LazyVim core sync:  $( [[ "$SKIP_SYNC" -eq 1 ]] && echo SKIP || ([[ "$sync_ok" -eq 1 ]] && echo PASS || echo FAIL) )
Tree-sitter CLI:    $( [[ -n "${TS_CLI_VERIFY_STATUS:-}" ]] && ts_cli_verify_summary_label || echo SKIP) )
Tree-sitter runtime: $( [[ "$SKIP_SYNC" -eq 1 ]] && echo SKIP || ([[ "$parser_ok" -eq 1 ]] && echo PASS || echo FAIL) )
Mason/LSP tools:    $( [[ "$SKIP_SYNC" -eq 1 ]] && echo SKIP || ([[ "$mason_ok" -eq 1 ]] && echo PASS || echo FAIL) )

Disk usage:
  nvim data:  $(format_bytes "$(disk_usage_bytes "${XDG_DATA_HOME:-$HOME/.local/share}/nvim")")
  nvim cache: $(format_bytes "$(disk_usage_bytes "${XDG_CACHE_HOME:-$HOME/.cache}/nvim")")

Nerd Font recommended for complete icon display (not required).

Next steps:
  1. Run: nvim
  2. Inside nvim: :LazyHealth
  3. Measure disk: ./lazyvim/measure-disk.sh

EOF
}

main() {
  local disk_before=0

  load_install_conf
  check_platform
  check_not_root_for_user_phase "$@"
  parse_args "$@"

  DRY_RUN="$DRY_RUN" bash "$SCRIPT_DIR/cleanup-leftovers.sh"

  disk_before="$(disk_usage_bytes "${XDG_DATA_HOME:-$HOME/.local/share}/nvim")"
  disk_before=$((disk_before + $(disk_usage_bytes "${XDG_CACHE_HOME:-$HOME/.cache}/nvim")))

  log "estimated footprint before install: $(format_bytes "$disk_before") (nvim data+cache only)"
  log "plugins/Mason will download on first sync (typically hundreds of MB, not GB)"

  check_neovim
  ensure_local_bin_path

  run bash "$SCRIPT_DIR/install-system-deps.sh"
  run bash "$SCRIPT_DIR/install-tree-sitter-cli.sh"
  check_node_environment
  prepare_lazyvim_config

  if [[ "$SKIP_SYNC" -eq 0 ]]; then
    DRY_RUN="$DRY_RUN" bash "$SCRIPT_DIR/sync-lazyvim.sh"
  else
    log "skipping headless sync (--skip-sync)"
  fi

  if [[ "$DRY_RUN" -eq 1 ]]; then
    log "dry-run complete"
    exit 0
  fi

  verify_installation
}

main "$@"
