-- Generated by lazyvim/install-lazyvim.sh
-- Edit lazyvim/install.conf and re-run the installer to change extras.
-- LazyVim-lite ignores this file (profile-aware guard).

local profile = require("config.nvim-profile")
if not profile.is("lazyvim") then
  return {}
end

return {
  { import = "lazyvim.plugins.extras.lang.typescript" },
  { import = "lazyvim.plugins.extras.lang.python" },
  { import = "lazyvim.plugins.extras.lang.json" },
  { import = "lazyvim.plugins.extras.lang.yaml" },
  { import = "lazyvim.plugins.extras.lang.toml" },
  { import = "lazyvim.plugins.extras.lang.tailwind" },
  { import = "lazyvim.plugins.extras.lang.git" },
  { import = "lazyvim.plugins.extras.lang.docker" },
}
